/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'I2CTester-Bairan-Y9000X' 
 * Target:  'I2CTester' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H



#endif /* RTE_COMPONENTS_H */
